apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica
  labels:
    app: git
spec:
  replicas: 5
  selector:
    matchLabels:
      app: git
  template:
    metadata:
      labels:
        app: git
    spec:
      containers:
      - name: con1
        image: nginx:latest
